nwolverson/purescript-language-server

.gitignore
src/LanguageServer/IdePurescript/Imports.purs

Depends on https://github.com/nwolverson/purescript-ide-purescript-core/pull/11

Support addQualifiedImport

---

src/LanguageServer/IdePurescript/Completion.purs
src/LanguageServer/IdePurescript/SuggestionRank.purs

Depends on https://github.com/nwolverson/purescript-ide-purescript-core/pull/13
The ranking format is kind of weird. VSCode uses `rankText` to affect ordering (actual ordering of the results has no effect), so I'm just returning  "a" or "z", where "a" forces a higher ranking.

Add suggestion ranking heuristics

---

src/LanguageServer/IdePurescript/Tooltips.purs
src/LanguageServer/Types.purs

Old version:
New version (including clickable link if docs contains URL):

Add documentation to hover

---

src/LanguageServer/IdePurescript/Config.purs
src/LanguageServer/IdePurescript/Server.purs

For issue #43
If this is accepted, I can also put support into the atom and vscode plugins.

Add new config option for calling `spago sources` to get sources globs.

---

.gitignore
package-lock.json
package.json

This changes the `psc-package` task to be `spago` instead and adds both `spago` and `purescript` as dev dependencies.
I was getting errors running `npm install`.
```
npm install
> purescript-language-server@0.12.7 prepare /Users/mark/code/purescript-language-server
> run-s install:* build
> purescript-language-server@0.12.7 install:psc /Users/mark/code/purescript-language-server
> psc-package install
psc-package.json does not exist. Maybe you need to run psc-package init?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! purescript-language-server@0.12.7 install:psc: `psc-package install`
npm ERR! Exit status 1
```

Move to spago

---

.gitignore
package-lock.json
package.json
src/LanguageServer/Handlers.js
src/LanguageServer/Handlers.purs
src/LanguageServer/Handlers.ts
src/LanguageServer/IdePurescript/FoldingRanges.purs
src/LanguageServer/IdePurescript/Main.purs
src/LanguageServer/Setup.js
src/LanguageServer/Setup.ts
src/LanguageServer/Types.purs
src/LanguageServer/Uri.js
src/LanguageServer/Uri.ts

This adds a folding range for imports (that means it's possible to "hide/show" all imports with the little caret left of the line or a command).
This extension is already really good at managing imports and I'm more than happy to delegate this 💩 to a computer. However, the structure of PureScript programs requires imports to be one of the first things one sees when opening a file. Being able to automatically hide them mitigates this problem.
It is quite naïvely implemented (it goes from the first line that starts with `import ` until the last that does).
I also updated some dependencies.
Note that this change is on top of my PR that ports to spago.

Add folding ranges

---

src/LanguageServer/IdePurescript/Main.purs
src/LanguageServer/IdePurescript/Server.purs

I realized this probably needs to be done. I also realized that it seems like WSL2 might not pass env vars correctly, but I have to dig into this more.

check if PURS_IDE_SOURCES env var is being used in startup

---

package-lock.json
package.json
spago.dhall
src/IdePurescript/Modules.purs

If you go back and forth between files quickly using go to definition and go back, then extension features like go to definition, hover, etc. stop working. It gets fixed once you close the file and load it back again.
The following changes fixes the problem.

fix concurrency issue in go to definition

---

src/LanguageServer/IdePurescript/Main.purs

If `getTextDocUri` will not be passed to `runHandler`, then `updateModules` will not be triggered, and `modules` and `moduleFile` not be updated. Passing it also for this handler will make `show usages/references` work, when opening a file.
1. Open https://github.com/jonasbuntinx/purescript-react-realworld/blob/d59eaf5c3431ea465db792f291eede42dc6190c7/src/Conduit/Page/Article.purs#L52
2. Wait 10 seconds
3. Trigger "Show usages" for `mkArticlePage`
Before this PR, it won't work. With this PR it'll jump to where it is used.
Closes #88

Find references will work immediately

---

src/LanguageServer/IdePurescript/CodeActions.purs

This is one of the cases where I double check a hundred times, just to make sure I'm not mistaken :D 
I'm pretty sure though, that the current/previous implementation of `intersects` itself is wrong.
To have `start <= end' && start' >= end` (current implementation) be true, it would look like this. But the ranges wouldn't intersect.
```
[start]--------[end]
[start']----------[end']
````
I think it should be: `start <= end' && start' <= end`

Codeaction: Fix intersection of two ranges

---

src/LanguageServer/IdePurescript/Main.purs

I've been working on [purs-nix](https://github.com/ursi/purs-nix) which is a tool that lets you manage your purescript projects with just nix. Because of this, there is no `bower.json`, `psc-package.json`, or `spago.dhall` in my directories and the language server is complaining. This fixes the issue by adding `flake.nix` to the list of files it looks for.

Add flake.nix to list of files for detecting projects

---

src/LanguageServer/IdePurescript/Main.purs

**purs-nix** is now compatible with Nix stable, which uses a `shell.nix` file instead of `flake.nix`

Add shell.nix to the list of files for detecting projects

---

src/LanguageServer/tsconfig.json

This is just to make `tsc` always generate LF line endings (actual on windows) so it doesn't differ from existing in the git. Also, it updates file formatting to standard 2-spaces indent.

make tsc generate LF newlines

---

.vscode/settings.json
spago.dhall
src/IdePurescript/Build.purs

This should fix https://github.com/nwolverson/purescript-language-server/issues/133.
Also it adds `addNpmPath` setting for the project itself, as it seems actual, and adds `debug` package that is useful for debugging.

Fix windows env path

---

src/LanguageServer/IdePurescript/Main.purs
src/LanguageServer/tsconfig.json

Files that are opened in the editor automatically rebuilt (to show diagnostics without the need to update and save it), but it is not so actual for the library sources, esp considering that compiler [currently rebuilds if they are not changed ](https://github.com/purescript/purescript/issues/4066)(and rebuild is actually not needed to be rebuilt, that may unnecessarily trigger file watching tools). So this checks if the file path contains `.spago` or `bower_components` to skip it.

Skip lib sources when rebuilding opened files

---

.vscode/tasks.json
package-lock.json
package.json
src/LanguageServer/Protocol/Console.js
src/LanguageServer/Protocol/Console.ts
src/LanguageServer/Protocol/DocumentStore.js
src/LanguageServer/Protocol/DocumentStore.ts
src/LanguageServer/Protocol/Handlers.js
src/LanguageServer/Protocol/Handlers.ts
src/LanguageServer/Protocol/Setup.js
src/LanguageServer/Protocol/Setup.ts
src/LanguageServer/Protocol/TextDocument.js
src/LanguageServer/Protocol/TextDocument.ts
src/LanguageServer/Protocol/Uri.js
src/LanguageServer/Protocol/Uri.ts
src/LanguageServer/Protocol/Window.js
src/LanguageServer/Protocol/Window.ts
src/LanguageServer/Protocol/Workspace.js
src/LanguageServer/Protocol/Workspace.ts

- Adds .prettierrc (default) because some prettier setups check its existence for formatting to work, and it is more convenient to have settings in a separate file.
- Adds `format:js` command to package.json
- Formats ts/js with prettier
- Updates TypeScript version (because there were type errors in newly installed vscode-language deps during tsc compilation)
- Adds tsc compilation task in `.vscode/tasks.json` (to run auto compilation while development)

Format ts/js with prettier, update TS

---

package.json

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
Optional chaining is not supported by Node 12. 14 is current LTS so no big issue.

Node 14+ is required engine

---

.gitignore
.vscode/tasks.json
cli.js
package-lock.json
package.json
server.js
src/LanguageServer/IdePurescript/Main.js
src/LanguageServer/tsconfig.json

Adds esbuild bundling to `bundle.js`, `server.js` now in the repo.
VScode tasks.json includes two watch tasks (tsc and bundle), that can be run in dev mode. Error matcher `$esbuild-watch` is available through vscode extension.
`Main.js` was modified to prevent `require` resolution by `esbuild` and proper possible exception handling.
Made minified `esbuild` bundle with external source maps in build mode.

Migrate bundling to esbuild

---

package-lock.json
src/LanguageServer/IdePurescript/Assist.purs
src/LanguageServer/IdePurescript/Main.purs
src/LanguageServer/IdePurescript/WatchedFiles.purs
src/LanguageServer/Protocol/Types.purs

This change inserts
```purescript
module Path.From.Src.Directory where
import Prelude
```
when opening empty `.purs` files. This makes these files compile
instead of being invalid modules.
https://user-images.githubusercontent.com/1588055/144762071-9729f321-c469-4eba-af81-0443f0530d94.mov

Insert module header into empty .purs files automatically

---

src/LanguageServer/IdePurescript/Config.purs

Hey,
Before looking it up, my first try to disable an existing formatter was to set the field to `""`. Later I found out there is `"none"`.
I would also interpret `""` as `NoFormatter`, but it's up to you if you think that's a good idea or not :)

Config: Empty formatter, no formatter

---

README.md

Ref #179 
Add `formatter` option for Coc.nvim in README.md
This is important for Apple Silicon users as purty does not provide a arm64 build for it.

Add `formatter` option in README

---

src/LanguageServer/Protocol/Setup.js
src/LanguageServer/Protocol/Setup.ts

Currently the language servers sends `TextDocumentSyncKind` as its `textDocumentSync` capability.
The current LSP spec (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverCapabilities) expects a `TextDocumentSyncOptions` object instead.
`TextDocumentSyncKind` doesn't appear to be deprecated, but it's still accepted only for backwards compatibility.
This prevents some clients (for example the helix editor) from working with the purescript language server.
I have made some tests, and this looks like the minimal working config that vscode, emacs and helix accept happily. I'm a bit confused, as these options should correspond to a `TextDocumentSyncKind.None` and the server is sending `TextDocumentSyncKind.Full` now.

Update the textDocumentSync capability to spec v3

---

src/LanguageServer/IdePurescript/Build.purs
src/LanguageServer/IdePurescript/FileTypes.purs
src/LanguageServer/IdePurescript/Main.purs
src/LanguageServer/IdePurescript/Types.purs
src/LanguageServer/IdePurescript/WatchedFiles.purs
test/Main.purs

* Modification of JS file triggers evaluation of associated .purs files (same name and path save the extension) if it exists
* Motivated by a need for better user interface in IDE when authoring FFI

Add basic support for JavaScript files

---

package-lock.json
package.json
packages.dhall
spago.dhall
src/IdePurescript/Modules.js
src/IdePurescript/Modules.purs
src/IdePurescript/PscIde.purs
src/IdePurescript/Tokens.purs
src/LanguageServer/IdePurescript/Main.purs
src/LanguageServer/IdePurescript/Rename.purs
src/LanguageServer/IdePurescript/Rename/CST.purs
src/LanguageServer/IdePurescript/Types.purs
src/LanguageServer/Protocol/Handlers.js
src/LanguageServer/Protocol/Handlers.purs
src/LanguageServer/Protocol/Handlers.ts
src/LanguageServer/Protocol/Setup.js
src/LanguageServer/Protocol/Setup.ts
src/LanguageServer/Protocol/Text.purs
src/LanguageServer/Protocol/Types.purs
src/LanguageServer/Protocol/Window.ts
src/LanguageServer/Protocol/Workspace.js
src/LanguageServer/Protocol/Workspace.ts
test/Fixture/RenameA.purs
test/Fixture/RenameB.purs
test/Rename.purs

This PR adds rename refactoring capabilities to LS. It's supposed to support renaming of all kinds of exported identifiers (potentially even type classes with members 🤪), though due to the purs ide usage API issues it is limited when used with the current compiler version. Anyway it is still capable of renaming value/function identifiers and type constructors, though types and operators can not be renamed. 
I actually have ready updates for the compiler to fix those issues with the usage API.
Tests are in test\Rename.purs - all tests pass only with the updated compiler version with usages api fixed.
This doesn't currently support renaming of local/private identifiers. 
This PR is based on #194 (tidy formatting PR). All the changes referred to refactoring are in the single latest commit …

Rename refactoring capablities v1
